# Generated by Django 4.0.5 on 2022-07-21 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testenglish', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
